# LEKCE 2

# Podmíněný výběr tučňáků

In [1]:
import pandas as pd
data = pd.read_csv("https://raw.githubusercontent.com/allisonhorst/palmerpenguins/master/inst/extdata/penguins.csv")

### Jaký je průměrný `body_mass_g` tučňáků v datasetu?

Použijte metodu `describe()` pro zobrazení základních statistik.

In [2]:
# data.describe()
# data['body_mass_g'].describe()
data['body_mass_g'].describe()['mean']

np.float64(4201.754385964912)

### Jaká je maximální délka křídel (`flipper_length_mm`) tučňáků v datasetu?

Použijte metodu `describe()` pro zobrazení základních statistik.

Výsledek zaokrouhli na celé číslo.

In [3]:
data['flipper_length_mm'].describe()['max']
# round(data['flipper_length_mm'].describe()['max'])

np.float64(231.0)

### Které druhy tučňáků jsou zastoupeny v datasetu?

Použijte metodu `unique()`.

In [4]:
data['species'].unique()

<StringArray>
['Adelie', 'Gentoo', 'Chinstrap']
Length: 3, dtype: str

### Které druhy tučňáka mají zastoupení na ostrově Dream?

In [5]:
data[data["island"] == 'Dream']["species"].unique()

<StringArray>
['Adelie', 'Chinstrap']
Length: 2, dtype: str

### Kolik tučňáků má hmotnost vyšší než 5000 gramů?

Použijte podmíněný výběr k filtraci tučňáků s hmotností vyšší než 5000 gramů a spočítejte počet takových záznamů.

In [6]:
data[data["body_mass_g"] > 5_000] #.shape[0]

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex,year
153,Gentoo,Biscoe,50.0,16.3,230.0,5700.0,male,2007
155,Gentoo,Biscoe,50.0,15.2,218.0,5700.0,male,2007
156,Gentoo,Biscoe,47.6,14.5,215.0,5400.0,male,2007
159,Gentoo,Biscoe,46.7,15.3,219.0,5200.0,male,2007
161,Gentoo,Biscoe,46.8,15.4,215.0,5150.0,male,2007
...,...,...,...,...,...,...,...,...
267,Gentoo,Biscoe,55.1,16.0,230.0,5850.0,male,2009
269,Gentoo,Biscoe,48.8,16.2,222.0,6000.0,male,2009
273,Gentoo,Biscoe,50.4,15.7,222.0,5750.0,male,2009
274,Gentoo,Biscoe,45.2,14.8,212.0,5200.0,female,2009
275,Gentoo,Biscoe,49.9,16.1,213.0,5400.0,male,2009

### Kolik tučňáků má hmotnost menší než 3500 gramů a délku křídla (`flipper`) větší než 200 mm?

Použijte podmíněný výběr pro najití tučňáků splňujících obě kritéria a spočítejte, kolik takových záznamů existuje.

In [7]:
data[(data["body_mass_g"] < 3_500) & (data["flipper_length_mm"] > 200)] #.shape[0]

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex,year
340,Chinstrap,Dream,43.5,18.1,202.0,3400.0,female,2009

### Kolik tučňáků z ostrova Torgensen má ve sloupci `sex` uvedenu hodnotu `female`?

In [14]:
data[(data["island"] == "Torgersen") & (data["sex"] == "female")].shape

(24, 8)

### Který rok má nejvíce záznamů?

In [9]:
data["year"].value_counts()#.head(1)

year
2009    120
2008    114
2007    110
Name: count, dtype: int64

### Jaká je mediánová hodnota `body_mass_g` tučňáků v datasetu?

Použijte metodu `describe()` pro zobrazení základních statistik.

50\.	percentil je totéž jako medián.

In [10]:
data["body_mass_g"].describe()

count     342.000000
mean     4201.754386
std       801.954536
min      2700.000000
25%      3550.000000
50%      4050.000000
75%      4750.000000
max      6300.000000
Name: body_mass_g, dtype: float64

In [11]:
# Jak se dostat ke konkrétní hodnotě?
# Kód volá metodu describe() na konkrétním sloupci body_mass_g ve dataframe data
# Pomocí indexu ['50%'] vybírá medián (50. percentil)
data["body_mass_g"].describe()['50%']

# Kód volá metodu describe() na celém dataframe data, čímž získá popisné statistiky pro všechny numerické sloupce v dataframe
# Pomocí .loc[] se specifikuje, že chcete hodnotu z řádku '50%' (což odpovídá mediánu) a sloupce 'body_mass_g'
data.describe().loc['50%', 'body_mass_g']

np.float64(4050.0)