|# Nadpis
**analyza**

In [ ]:
import pandas as pd

In [ ]:
food = pd.read_csv('food_sample_100.csv')

In [ ]:
food # zobrazí tabulku (prvních pět a posledních pět záznamů) a sloupce

,fdc_id,data_type,description,food_category_id,publication_date
0,2644829,sub_sample_food,"lentils, dry",16.0,2023-10-19
1,2347263,sub_sample_food,heavy cream,1.0,2022-10-28
2,2261954,sub_sample_food,"Flour, potato",11.0,2022-04-28
3,321470,sub_sample_food,"Salt, Iodized",2.0,2019-04-01
4,322951,sub_sample_food,Hot dogs beef,7.0,2019-04-01
...,...,...,...,...,...
95,2260615,sub_sample_food,"Yogurt, whole milk, plain",1.0,2022-04-28
96,2646468,sub_sample_food,"chicken, breast, boneless, skinless",5.0,2023-10-19
97,2647032,sub_sample_food,"pork, loin, boneless",10.0,2023-10-19
98,2349564,sub_sample_food,"Oats, whole grain, rolled, old fashioned",20.0,2022-10-28
99,328565,market_acquisition,"Cheese, cheddar, mild, block/chunk, store bran...",1.0,2019-04-01

In [ ]:
# Indexy

food = food.set_index("fdc_id")
food = food.reset_index()
food

,fdc_id,data_type,description,food_category_id,publication_date
0,2644829,sub_sample_food,"lentils, dry",16.0,2023-10-19
1,2347263,sub_sample_food,heavy cream,1.0,2022-10-28
2,2261954,sub_sample_food,"Flour, potato",11.0,2022-04-28
3,321470,sub_sample_food,"Salt, Iodized",2.0,2019-04-01
4,322951,sub_sample_food,Hot dogs beef,7.0,2019-04-01
...,...,...,...,...,...
95,2260615,sub_sample_food,"Yogurt, whole milk, plain",1.0,2022-04-28
96,2646468,sub_sample_food,"chicken, breast, boneless, skinless",5.0,2023-10-19
97,2647032,sub_sample_food,"pork, loin, boneless",10.0,2023-10-19
98,2349564,sub_sample_food,"Oats, whole grain, rolled, old fashioned",20.0,2022-10-28
99,328565,market_acquisition,"Cheese, cheddar, mild, block/chunk, store bran...",1.0,2019-04-01

In [ ]:
food.info() #informace o tabulce a datasetu
food.head(10) #vypíše prvních 10 řádků,může být i jiné číslo
food.tail(5) #vypiš posledních pět záznamů z datasetu
food.sample() #random číslo z datasetu
food.sample(5) #random pět čísel

<class 'pandas.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 5 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   fdc_id            100 non-null    int64
 1   data_type         100 non-null    str
 2   description       100 non-null    str
 3   food_category_id  99 non-null     float64
 4   publication_date  100 non-null    str
dtypes: float64(1), int64(1), str(3)
memory usage: 4.0 KB

,fdc_id,data_type,description,food_category_id,publication_date
23,2003754,sample_food,"ORANGE JUICE, REFRIGERATED, NO PULP, NOT FORTI...",9.0,2021-10-15
61,2003818,sample_food,"TOMATO JUICE, SHELF STABLE, FROM CONCENTRATE, ...",11.0,2021-10-15
17,2514917,sub_sample_food,"Beef, ground, grass-fed, 90% lean, 10% fat, raw",13.0,2023-04-20
48,2259344,sub_sample_food,"carrots, mature, raw",11.0,2022-04-28
50,328069,sub_sample_food,"Fatty Acids, Cheddar cheese, sliced, store bra...",1.0,2019-04-01

In [ ]:
food.shape #vrátí kolik je řádků a kolik sloupečků-oboje
food.shape[0] #počet řádků
food.shape[1] #počet sloupců
food.columns #seznam sloupečků,které mám v datasetu

Index(['fdc_id', 'data_type', 'description', 'food_category_id',
       'publication_date'],
      dtype='str')

In [ ]:
food["description"] #tzv.series,získám vybrání jednoho sloupečku

seznam_sloupcu = ["description" , "fdc_id"]

food[["description" , "fdc_id"]]

                                          description   fdc_id
0                                        lentils, dry  2644829
1                                         heavy cream  2347263
2                                       Flour, potato  2261954
3                                       Salt, Iodized   321470
4                                       Hot dogs beef   322951
..                                                ...      ...
95                          Yogurt, whole milk, plain  2260615
96                chicken, breast, boneless, skinless  2646468
97                               pork, loin, boneless  2647032
98           Oats, whole grain, rolled, old fashioned  2349564
99  Cheese, cheddar, mild, block/chunk, store bran...   328565

[100 rows x 2 columns]

In [ ]:
 # CVIČENÍ Titanic 

import pandas as pd
titanic = pd.read_csv("titanic.csv")
titanic.columns
titanic.shape
titanic.info()

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    str
 4   Sex          891 non-null    str
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    str
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    str
 11  Embarked     889 non-null    str
dtypes: float64(2), int64(5), str(5)
memory usage: 83.7 KB

In [ ]:

import pandas as pd

data_aapl = pd.read_csv("aapl_daily_2y.csv")
data_aapl = data_aapl.set_index("date")
data_aapl.shape[0]  # počet řádků v tabulce
data_aapl.shape[1]  # počet sloupců v tabulce
data_aapl.columns  # názvy všech sloupců

start_date = data_aapl.index[0]  # datum začátku sledovaného období
end_date = data_aapl.index[-1]  # datum konce sledovaného období

data_aapl.head()
data_aapl.tail()

start_close = data_aapl["close"].iat[0] # zavírací cena na začátku období
end_close = data_aapl["close"].iat[-1]  # zavírací cena na konci období

initial_investment = 9000  # výchozí investice v USD
share_count = initial_investment / start_close  # počet nakoupených akcií
final_value = share_count * end_close  # hodnota investice na konci období

profit_percent = (final_value - initial_investment) / initial_investment * 100 # zisk v procentech -- cvičení Apple --

In [ ]:
# CVIČENÍ A Song of Ice and Fire 

import pandas as pd

data = pd.read_csv("character-deaths.csv")
data = data.set_index("Name")

sloupce = data.columns.tolist()
# Informace o smrti Hali
hali = data.loc["Hali"]

hali

# Řádky mezi "Gevin Harlaw" a "Gillam".
usek = data.loc["Gevin Harlaw":"Gillam"]

usek

# Řádky mezi "Gevin Harlaw" a "Gillam", sloupec "Death Year".
deaths = data.loc["Gevin Harlaw":"Gillam", "Death Year"]

deaths

# V jakých knihách se postava vyskytují postavy "Gevin Harlaw" až "Gillam".
books = data.loc["Gevin Harlaw":"Gillam", "GoT":"DwD"]

books

                     GoT  CoK  SoS  FfC  DwD
Name
Gevin Harlaw           0    1    0    0    0
Ghael                  0    0    1    0    1
Ghost of High Heart    0    0    1    0    0
Gillam                 0    0    0    1    0

In [ ]:
 # QUIZ 1 

import pandas as pd 

data = pd.read_csv ("penguins.txt")

data.shape[0]
data.shape[1]
data.head(10)

data.info()

data.columns

<class 'pandas.DataFrame'>
RangeIndex: 344 entries, 0 to 343
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   species            344 non-null    str
 1   island             344 non-null    str
 2   bill_length_mm     342 non-null    float64
 3   bill_depth_mm      342 non-null    float64
 4   flipper_length_mm  342 non-null    float64
 5   body_mass_g        342 non-null    float64
 6   sex                333 non-null    str
 7   year               344 non-null    int64
dtypes: float64(4), int64(1), str(3)
memory usage: 21.6 KB

Index(['species', 'island', 'bill_length_mm', 'bill_depth_mm',
       'flipper_length_mm', 'body_mass_g', 'sex', 'year'],
      dtype='str')