In [215]:
import pandas as pd

In [216]:
food_sample_100 = pd.read_csv("food_sample_100.csv")
food_other = pd.read_csv("food_other.csv")

In [217]:
food_sample_100.columns

Index(['fdc_id', 'data_type', 'description', 'food_category_id',
       'publication_date'],
      dtype='str')

In [218]:
food_other.columns

Index(['fdc_id', 'data_type', 'description', 'food_category_id',
       'publication_date'],
      dtype='str')

In [219]:
# v SQL UNION

# v pandas tj. CONCAT

food = pd. concat ([food_sample_100, food_other], ignore_index=True)
food.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 5 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   fdc_id            10000 non-null  int64
 1   data_type         10000 non-null  str
 2   description       10000 non-null  str
 3   food_category_id  128 non-null    float64
 4   publication_date  10000 non-null  str
dtypes: float64(1), int64(1), str(3)
memory usage: 390.8 KB

In [220]:
food_other

,fdc_id,data_type,description,food_category_id,publication_date
0,1106032,branded_food,"Chicken, FC Beer Battered Boneless Wing Fritte...",NaN,2020-11-13
1,1107191,branded_food,"MARINARA SAUCE, MARINARA",NaN,2020-11-13
2,1107295,branded_food,"ORIGINAL ROUNDS TORTILLA CHIPS, ORIGINAL",NaN,2020-11-13
3,1107475,branded_food,"NACHO QUESO SUPREME DIP, NACHO QUESO SUPREME",NaN,2020-11-13
4,1107528,branded_food,"CLASSIC JUMBO FRANKS, CLASSIC",NaN,2020-11-13
...,...,...,...,...,...
9895,2661515,branded_food,"CHAI LATTE SUGAR FREE BLACK TEA CONCENTRATE, C...",NaN,2023-10-26
9896,2661730,branded_food,"APPLE BANANA ORGANIC FRUIT POUCHES, APPLE BANANA",NaN,2023-10-26
9897,2661782,branded_food,"SPINACH ORGANIC PUREE, SPINACH",NaN,2023-10-26
9898,2662107,branded_food,LIGHT MOZZARELLA LOW-MOISTURE PART-SKIM STRING...,NaN,2023-10-26
9899,2662182,branded_food,"ITALIAN-STYLE DICED TOMATOES WITH BASIL, GARLI...",NaN,2023-10-26

In [221]:
food_nutrient = pd.read_csv ("food_nutrient.csv")
food_nutrient.head(2)

,fdc_id,nutrient_id,amount,data_points,derivation_id,min,max,median,loq,footnote,min_year_acquired,name,unit_name
0,1106032,1257,NaN,NaN,71.0,NaN,NaN,NaN,NaN,NaN,NaN,"Fatty acids, total trans",G
1,1107191,1257,NaN,NaN,70.0,NaN,NaN,NaN,NaN,NaN,NaN,"Fatty acids, total trans",G

In [222]:
# funkce merge / JOIN v SQL, on-klíč propojení možné také jako "primary key"

food_merged = pd.merge (food, food_nutrient, on="fdc_id", how="left")
food_merged

# inner 135.336 rows
# left 135.349 rows

,fdc_id,data_type,description,food_category_id,publication_date,nutrient_id,amount,data_points,derivation_id,min,max,median,loq,footnote,min_year_acquired,name,unit_name
0,2644829,sub_sample_food,"lentils, dry",16.0,2023-10-19,1101.0,1.58,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,"Manganese, Mn",MG
1,2347263,sub_sample_food,heavy cream,1.0,2022-10-28,1258.0,20.00,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,"Fatty acids, total saturated",G
2,2261954,sub_sample_food,"Flour, potato",11.0,2022-04-28,1102.0,21.80,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,"Molybdenum, Mo",UG
3,321470,sub_sample_food,"Salt, Iodized",2.0,2019-04-01,1051.0,0.69,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,Water,G
4,321470,sub_sample_food,"Salt, Iodized",2.0,2019-04-01,1007.0,98.40,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,Ash,G
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
135344,2662182,branded_food,"ITALIAN-STYLE DICED TOMATOES WITH BASIL, GARLI...",NaN,2023-10-26,1005.0,4.07,NaN,70.0,NaN,NaN,NaN,NaN,NaN,NaN,"Carbohydrate, by difference",G
135345,2662182,branded_food,"ITALIAN-STYLE DICED TOMATOES WITH BASIL, GARLI...",NaN,2023-10-26,1004.0,0.41,NaN,70.0,NaN,NaN,NaN,NaN,NaN,NaN,Total lipid (fat),G
135346,2662182,branded_food,"ITALIAN-STYLE DICED TOMATOES WITH BASIL, GARLI...",NaN,2023-10-26,1003.0,0.81,NaN,70.0,NaN,NaN,NaN,NaN,NaN,NaN,Protein,G
135347,2662182,branded_food,"ITALIAN-STYLE DICED TOMATOES WITH BASIL, GARLI...",NaN,2023-10-26,1235.0,0.00,NaN,70.0,NaN,NaN,NaN,NaN,NaN,NaN,"Sugars, added",G
135348,2662182,branded_food,"ITALIAN-STYLE DICED TOMATOES WITH BASIL, GARLI...",NaN,2023-10-26,1114.0,0.00,NaN,70.0,NaN,NaN,NaN,NaN,NaN,NaN,Vitamin D (D2 + D3),UG

In [223]:
# cvičení Značky a výrobci

import pandas as pd

In [224]:
# DataFrame branded_food a zobrazení tabulky
branded_food = pd.read_csv ("branded_food.csv")
branded_food.head(2)

,fdc_id,brand_owner,brand_name,subbrand_name,gtin_upc,ingredients,not_a_significant_source_of,serving_size,serving_size_unit,household_serving_fulltext,branded_food_category,data_source,package_weight,modified_date,available_date,market_country,discontinued_date,preparation_state_code,trade_channel,short_description
0,1106032,BRAKEBUSH BROTHERS INC.,NaN,NaN,10038034720202,INGREDIENTS: BONELESS CHICKEN BREAST MEAT WITH...,NaN,85.0,g,NaN,Meat/Poultry/Other Animals Prepared/Processed,GDSN,NaN,2020-09-03,2020-11-13,United States,NaN,NaN,NaN,NaN
1,1107191,Mahco Inc,NaN,NaN,877448001674,"TOMATO PUREE (TOMATOES), CARROTS, ONIONS, SUN-...",NaN,125.0,g,NaN,Prepared Pasta & Pizza Sauces,LI,NaN,2020-09-22,2020-11-13,United States,NaN,NaN,NaN,NaN

In [225]:
branded_food ["brand_owner"]. value_counts().head (3) #Zjisti tři výrobce s největším počtem potravin v tabulce.

brand_owner
Wal-Mart Stores, Inc.    219
Target Stores            199
Meijer, Inc.             168
Name: count, dtype: int64

In [226]:
branded_food ["branded_food_category"]. value_counts().head (5) #Zjisti pět kategorií s největších počtem potravin v tabulce.

branded_food_category
Popcorn, Peanuts, Seeds & Related Snacks    504
Candy                                       415
Cheese                                      405
Ice Cream & Frozen Yogurt                   310
Cookies & Biscuits                          272
Name: count, dtype: int64

In [227]:
food_merged_brands = pd.merge(food_merged, branded_food, right_on="fdc_id", left_on="fdc_id")  
food_merged_brands 

# U výsledné tabulky food_merged_brands zkontroluj počet řádků a srovnej ho s původní tabulkou food_merged. Ubyly nějaké řádky? A čím to je?
print(food_merged_brands.shape)
print(food_merged.shape)

(129284, 36)
(135349, 17)

In [228]:
# Nyní proveď operaci merge znovu, ale s parametrem how nastaveným na hodnotu left. Zkontroluj počet řádků a porovnej ho s počtem řádků tabulky food_merged_brands. Proč se počet liší?

food_merged_brands = pd.merge(food_merged, branded_food, right_on="fdc_id", left_on="fdc_id", how="left")
print(food_merged_brands.shape)
print(food_merged.shape)

(135349, 36)
(135349, 17)

In [229]:
# cvičení Přejmenování sloupce z name na nutrient.name 

food_merged_brands = food_merged_brands.rename (columns={"name": "nutrient_name"})
food_merged_brands.columns

Index(['fdc_id', 'data_type', 'description', 'food_category_id',
       'publication_date', 'nutrient_id', 'amount', 'data_points',
       'derivation_id', 'min', 'max', 'median', 'loq', 'footnote',
       'min_year_acquired', 'nutrient_name', 'unit_name', 'brand_owner',
       'brand_name', 'subbrand_name', 'gtin_upc', 'ingredients',
       'not_a_significant_source_of', 'serving_size', 'serving_size_unit',
       'household_serving_fulltext', 'branded_food_category', 'data_source',
       'package_weight', 'modified_date', 'available_date', 'market_country',
       'discontinued_date', 'preparation_state_code', 'trade_channel',
       'short_description'],
      dtype='str')

In [230]:
# Neexitující sloupec a chování funkce rename 

food_merged_brands = food_merged_brands.rename (columns={"test": "nutrient_name"})
food_merged_brands.columns

# Metoda .rename() funguje na principu mapování. Prochází sloupce v tvém DataFrame, a pokud najde shodu s klíčem ve slovníku, přejmenuje ho.
# Pokud shodu nenajde (sloupec "test" v tabulce není), prostě tento požadavek ignoruje a pokračuje dál.
# Je to užitečné v situacích, kdy máš skript, který zpracovává různé tabulky – pokud tam sloupec je, přejmenuje se, pokud ne, kód "nespadne".

Index(['fdc_id', 'data_type', 'description', 'food_category_id',
       'publication_date', 'nutrient_id', 'amount', 'data_points',
       'derivation_id', 'min', 'max', 'median', 'loq', 'footnote',
       'min_year_acquired', 'nutrient_name', 'unit_name', 'brand_owner',
       'brand_name', 'subbrand_name', 'gtin_upc', 'ingredients',
       'not_a_significant_source_of', 'serving_size', 'serving_size_unit',
       'household_serving_fulltext', 'branded_food_category', 'data_source',
       'package_weight', 'modified_date', 'available_date', 'market_country',
       'discontinued_date', 'preparation_state_code', 'trade_channel',
       'short_description'],
      dtype='str')

In [231]:
# cvičení Odstranění sloupců 

# Níže je příklad použití metody drop(). Použijeme parametr columns, kterému zadáme seznam sloupců k odstranění.

# food_merged_brands = food_merged_brands.drop(columns=["sloupec_1", "sloupec_2"])
# Využij metodu k odstranění sloupců footnote a min_year_acquired.

food_merged_brands = food_merged_brands.drop(columns=["footnote", "min_year_acquired"])

food_merged_brands.columns

# food_merged_brands = food_merged_brands.drop(columns=["test", "min_year_acquired"])

# food_merged_brands.columns

# Co se stane, když do .drop() zadáš neexistující sloupec?
# Chová se úplně jinak než metoda .rename()
# Metoda .rename() neexistující sloupce ignoruje (neudělá nic)
# Metoda .drop() při zadání neexistujícího názvu vyhodí chybu (KeyError)

Index(['fdc_id', 'data_type', 'description', 'food_category_id',
       'publication_date', 'nutrient_id', 'amount', 'data_points',
       'derivation_id', 'min', 'max', 'median', 'loq', 'nutrient_name',
       'unit_name', 'brand_owner', 'brand_name', 'subbrand_name', 'gtin_upc',
       'ingredients', 'not_a_significant_source_of', 'serving_size',
       'serving_size_unit', 'household_serving_fulltext',
       'branded_food_category', 'data_source', 'package_weight',
       'modified_date', 'available_date', 'market_country',
       'discontinued_date', 'preparation_state_code', 'trade_channel',
       'short_description'],
      dtype='str')

In [232]:
## SHRNUTÍ PŘEDEŠLÉHO ##

# Načteme tabulky o potravinách
food_sample_100 = pd.read_csv("food_sample_100.csv")
food_other = pd.read_csv("food_other.csv")
# Sjednotíme tabulky o potravinách do jedné tabulky food
food = pd.concat([food_sample_100, food_other], ignore_index=True)
# Načteme data o výživných látkách
food_nutrient = pd.read_csv("food_nutrient.csv")
# Propojíme tabulky o potravinách a výživných látkách
food_merged = pd.merge(food, food_nutrient, on="fdc_id")
# Načteme tabulku o značkách potravin
branded_food = pd.read_csv("branded_food.csv")
# Propojíme tabulku o značkách potravin a tabulkou o potravinách a výživných látkách
food_merged_brands = pd.merge(food_merged, branded_food, right_on="fdc_id", left_on="fdc_id", how="left")
# Přejmenujeme sloupec name na nutrient_name
food_merged_brands = food_merged_brands.rename(columns={"name": "nutrient_name"})
# NEPOVINNÝ KROK: Odstraníme nepotřebné sloupce footnote a min_year_acquired
food_merged_brands = food_merged_brands.drop(columns=["footnote", "min_year_acquired"])

In [233]:
# Agregace a řazení-Agregace je operace, která "sloučí" více řádků tabulky do jednoho.U agregace většinou slučujeme řádky podle nějakého konkrétního sloupce.

# Najít potraviny s Proteiny --> PODMÍNKA
food_merged_brands_protein = food_merged_brands [food_merged_brands["nutrient_name"] == "Protein"]
# food_merged_brands_protein.info ()

# Rozdělit na kategorii ("branded_food_category") --> seskupení, GROUP BY V SQL
food_merged_brands_protein.groupby ("branded_food_category")

# Spočítat průměr (MEAN) za každou kategorii --> vyber "amount", počítej průměr (V PYTHON JE PRŮMĚR MEAN !!!POZOR!!!)
# food_merged_brands_protein.head() -- zobrazení tabulky,abych si našla podle čeho budu počítat průměr tj. podle amount 
food_merged_brands_protein.groupby ("branded_food_category") ["amount"].mean ()

# Seřadit pro přehlednost --> METODA SORT_VALUE()

# Řazení pomocí ASC(ascending),#.sort_values(ascending=False) zajistí řazení od největšího
# !!! POZOR !!! DESCENDING NEEXISTUJE ,řadíme tedy pomocí True/False !!!, head zajistí TOP 10 místo 193 řádků 

food_merged_brands_protein.groupby ("branded_food_category") ["amount"].mean().sort_values(ascending=False).head(10) 

# můžu napsat i tímto způsobem,vytvořit si proměnnou data_agg

data_agg = food_merged_brands_protein.groupby ("branded_food_category") ["amount"].mean()
data_agg.sort_values(ascending=False).head(10)

branded_food_category
Bacon                                                  45.200000
Green Supplements                                      44.590000
Drinks Flavoured - Ready to Drink                      32.900000
Energy, Protein & Muscle Recovery Drinks               31.831481
Bacon, Sausages & Ribs                                 27.239630
Canned Tuna                                            21.648889
Meat/Poultry/Other Animals  Prepared/Processed         21.522368
Nut & Seed Butters                                     20.651270
Cheese                                                 19.969457
Meat/Poultry/Other Animals – Unprepared/Unprocessed    19.640000
Name: amount, dtype: float64

In [234]:
# CVIČENÍ Lipidy a Tuky
# Vytvoř novou tabulku food_merged_brands_lipid, do které pomocí dotazu vlož pouze řádky, které mají jako název výživné látky hodnotu Total lipid (fat)
food_merged_brands_lipid = food_merged_brands[
    food_merged_brands["nutrient_name"] == "Total lipid (fat)"
]
food_merged_brands_lipid.head(3)

# Proveď agregaci podle návu kategorie a seřaď výslednou tabulku tak, aby nahoře byly vidět kategorie s největším počtem tuků.
food_merged_brands_lipid_agg = food_merged_brands_lipid.groupby(
    "branded_food_category"
)["amount"].mean()

food_merged_brands_lipid_agg.sort_values(ascending=False)

branded_food_category
Oils Edible                                        93.330000
Vegetable & Cooking Oils                           78.012391
Butter & Spread                                    66.552667
Butter/Butter Substitutes                          63.965000
Meat/Poultry/Other Animals – Prepared/Processed    59.520000
                                                     ...
Pickles/Relishes/Chutneys/Olives                    0.000000
Specialty Formula Supplements                       0.000000
Spreads                                             0.000000
Syrups & Molasses                                   0.000000
Water                                               0.000000
Name: amount, Length: 193, dtype: float64

In [235]:
# CVIČENÍ Výrobci a kategorie
# Jaký výrobce produkuje jaké typy potravin.
# Proveď agregaci tabulky food_merged_brands podle dvou sloupců: brand_owner a branded_food_category.
# Sloupce musíš metodě food_merged_brands zadat jako seznam, tj. musíš použít hranaté závorky.
# Vyber sloupec fdc_id pro provedení agregace a použij agregaci nunique(), který vrátí počet unikátních hodnot.
# Nakonec použij metodu sort_values s tím, že chceš data seřadit sestupně.

food_merged_brands.groupby(
    ["brand_owner", "branded_food_category"]
)["fdc_id"].nunique().sort_values(ascending=False)

brand_owner               branded_food_category
Ferrara Candy Company     Candy                              40
CAMPBELL SOUP COMPANY     Prepared Soups                     29
Wells Enterprises, Inc.   Ice Cream & Frozen Yogurt          24
Danone US, LLC            Yogurt                             24
Bimbo Bakeries USA, Inc.  Breads & Buns                      24
                                                             ..
Zachary Confections Inc   Chocolate                           1
ZOUP!                     Canned Soup                         1
ZOLA                      Plant Based Water                   1
A.J. Trucco, Inc.         Pre-Packaged Fruit & Vegetables     1
A. Zerega's Sons Inc      All Noodles                         1
Name: fdc_id, Length: 5892, dtype: int64

In [236]:
# CVIČENÍ Hlasy
import pandas as pd

data = pd.read_csv('votes.csv')
# data
# data.info()

#Celkový počet odevzdaných hlasů v jednotlivých letech.
data.groupby('year')['candidatevotes'].sum()

#Celkový počet odevzdaných hlasů pro kandidáty a kandidátky jednotlivých stran pro volby v roce 2020.
data[data['year']==2020].groupby('party_detailed')['candidatevotes'].sum().sort_values(ascending=False)

# Celkový počet odevzdaných hlasů pro kandidáty dvou hlavních stran (DEMOCRAT a REPUBLICAN) pro všechny volby od roku 1980.
year = 1980
filter = (data['party_detailed'].isin(['DEMOCRAT','REPUBLICAN'])) &  (data['year']>=year)
data[filter].groupby('year')['candidatevotes'].sum().sort_values(ascending=False)

#Celkový počet odevzdaných hlasů pro stát MONTANA pro všechny roky.
data[data['state']=='MONTANA']['candidatevotes'].sum()

np.int64(5194180)

In [260]:
# CVIČENÍ Vítězové

import pandas as pd

data=pd.read_csv("votes.csv")
data
# data.info()

# URČENÍ POŘADÍ - Tohle je "mozek" celého příkladu. Chceme vědět, kdo byl v každém státě první, druhý atd.
data["rank"] = data.groupby(["state", "year"])["candidatevotes"].rank(ascending=False)

# Následně vytvoř tabulku, která bude obsahovat vítěznou stranu v jednotlivých státech ve volbách v roce 2020.
winners_by_state_2020 = data[(data["rank"] == 1) & (data["year"] == 2020)][["state", "party_detailed"]]
winners_by_state_2020

# data["rank"] == 1: Vyber jen ty, kteří skončili na prvním místě (vítěze).
# & (data["year"] == 2020): A zároveň (symbol &) nás zajímá jen rok 2020.
# [["state", "party_detailed"]]: Z té výsledné tabulky nám ukaž jen dva sloupce – název státu a politickou stranu vítěze.

                     state party_detailed
3741               ALABAMA     REPUBLICAN
3745                ALASKA     REPUBLICAN
3752               ARIZONA       DEMOCRAT
3771              ARKANSAS     REPUBLICAN
3773            CALIFORNIA       DEMOCRAT
3784              COLORADO       DEMOCRAT
3807           CONNECTICUT       DEMOCRAT
3838              DELAWARE       DEMOCRAT
3842  DISTRICT OF COLUMBIA       DEMOCRAT
3850               FLORIDA     REPUBLICAN
3878               GEORGIA       DEMOCRAT
3881                HAWAII       DEMOCRAT
3890                 IDAHO     REPUBLICAN
3904              ILLINOIS       DEMOCRAT
3925               INDIANA     REPUBLICAN
3938                  IOWA     REPUBLICAN
3950                KANSAS     REPUBLICAN
3953              KENTUCKY     REPUBLICAN
3970             LOUISIANA     REPUBLICAN
3981                 MAINE       DEMOCRAT
3989              MARYLAND       DEMOCRAT
4014         MASSACHUSETTS       DEMOCRAT
4020              MICHIGAN       DEMOCRAT
4032             MINNESOTA       DEMOCRAT
4042           MISSISSIPPI     REPUBLICAN
4050              MISSOURI     REPUBLICAN
4061               MONTANA     REPUBLICAN
4067              NEBRASKA     REPUBLICAN
4073                NEVADA       DEMOCRAT
4078         NEW HAMPSHIRE       DEMOCRAT
4100            NEW JERSEY       DEMOCRAT
4109            NEW MEXICO       DEMOCRAT
4113              NEW YORK       DEMOCRAT
4137        NORTH CAROLINA     REPUBLICAN
4144          NORTH DAKOTA     REPUBLICAN
4148                  OHIO     REPUBLICAN
4158              OKLAHOMA     REPUBLICAN
4165                OREGON       DEMOCRAT
4171          PENNSYLVANIA       DEMOCRAT
4173          RHODE ISLAND       DEMOCRAT
4181        SOUTH CAROLINA     REPUBLICAN
4185          SOUTH DAKOTA     REPUBLICAN
4188             TENNESSEE     REPUBLICAN
4201                 TEXAS     REPUBLICAN
4222                  UTAH     REPUBLICAN
4228               VERMONT       DEMOCRAT
4252              VIRGINIA       DEMOCRAT
4256            WASHINGTON       DEMOCRAT
4264         WEST VIRGINIA     REPUBLICAN
4267             WISCONSIN       DEMOCRAT
4281               WYOMING     REPUBLICAN

In [237]:
# QUIZ 3

import pandas as pd

In [238]:
# Použij metodu concat a spoj všechny tučňáky do jednoho dataframu. Kolik má nový dataframe řádek? 344 

penguins_adelie = pd.read_csv ("penguins_adelie.csv")
penguins_gentoo = pd.read_csv ("penguins_gentoo.csv")
penguins_chinstrap = pd.read_csv ("penguins_chinstrap.csv")

penguins = pd.concat ([penguins_adelie, penguins_gentoo, penguins_chinstrap], ignore_index=True)
penguins.info()

<class 'pandas.DataFrame'>
RangeIndex: 344 entries, 0 to 343
Data columns (total 17 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   studyName            344 non-null    str
 1   Sample Number        344 non-null    int64
 2   Species              344 non-null    str
 3   Region               344 non-null    str
 4   Island               344 non-null    str
 5   Stage                344 non-null    str
 6   Individual ID        344 non-null    str
 7   Clutch Completion    344 non-null    str
 8   Date Egg             344 non-null    str
 9   Culmen Length (mm)   342 non-null    float64
 10  Culmen Depth (mm)    342 non-null    float64
 11  Flipper Length (mm)  342 non-null    float64
 12  Body Mass (g)        342 non-null    float64
 13  Sex                  334 non-null    str
 14  Delta 15 N (o/oo)    330 non-null    float64
 15  Delta 13 C (o/oo)    331 non-null    float64
 16  Comments             54 non-null     str
dtypes: float64(6), int64(1), str(10)
memory usage: 45.8 KB

In [239]:
# zkopírováno z kvízu 

island_data = {
    'Island': ['Torgersen', 'Biscoe', 'Dream'],
    'Latitude': [-64.7667, -66.0000, -64.7333],
    'Longitude': [-64.0667, -66.0000, -64.2333],
    'Location': [
        'Torgersen Island, near Palmer Station on the Antarctic Peninsula, close to Anvers Island',
        'Biscoe Islands, an archipelago off the west coast of the Antarctic Peninsula, south of the Palmer Archipelago',
        'Dream Island, part of the Argentine Islands, located near the western side of the Antarctic Peninsula'
    ]
} 

penguin_islands_df = pd.DataFrame(island_data)

In [240]:
# 1. Propojení tabulek, Pomocí metody merge připoj data o ostrovech k hlavnímu dataframu

merged_df = penguins.merge(penguin_islands_df, on='Island')
merged_df

# 2 Jaká je průměrná hodnota Latitude ve spojeném dataframu?
prumer = merged_df["Latitude"].mean()
prumer

np.float64(-65.35696976744185)

In [ ]:
# Agregace QUIZ 3 (použití jiného datasetu z minulých lekcí)

import pandas as pd

In [242]:
penguins = pd.read_csv ("penguins.txt")
penguins

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex,year
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,male,2007
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,female,2007
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,female,2007
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN,2007
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,female,2007
...,...,...,...,...,...,...,...,...
339,Chinstrap,Dream,55.8,19.8,207.0,4000.0,male,2009
340,Chinstrap,Dream,43.5,18.1,202.0,3400.0,female,2009
341,Chinstrap,Dream,49.6,18.2,193.0,3775.0,male,2009
342,Chinstrap,Dream,50.8,19.0,210.0,4100.0,male,2009
343,Chinstrap,Dream,50.2,18.7,198.0,3775.0,female,2009

In [250]:
# Existují v datasetu chybějící hodnoty? Pokud ano, ve kterých sloupcích?
# Můžeš použít funkci .isnull() na rozpoznávání chybějících hodnot a pak sečíst jejich výskyt .sum()

penguins.isnull()
penguins.isnull().sum()

species               0
island                0
bill_length_mm        2
bill_depth_mm         2
flipper_length_mm     2
body_mass_g           2
sex                  11
year                  0
dtype: int64

In [244]:
# Jaké jsou průměrné hodnoty mean() hmotnosti tučňáků podle jejich druhu? Která odpověď je správně?

# Seskupíme data podle sloupce 'species', Seskupení dat (groupby)
seskupeno = penguins.groupby('species')

# Výběr sloupce a výpočet průměru (mean)
prumer = penguins.groupby('species')['body_mass_g'].mean()
prumer

species
Adelie       3700.662252
Chinstrap    3733.088235
Gentoo       5076.016260
Name: body_mass_g, dtype: float64

In [245]:
# Který druh tučňáka má největší maximální hmotnost a jaká je tato hmotnost?
penguins.groupby("species")["body_mass_g"].max().sort_values(ascending=False) # ascending=False --> řadí data sestupně (od největšího)

species
Gentoo       6300.0
Chinstrap    4800.0
Adelie       4775.0
Name: body_mass_g, dtype: float64

In [251]:
# Jaký je počet tučňáků podle jejich pohlaví v každém druhu? 
penguins.groupby(["species", "sex"]).size().sort_values(ascending=False)

species    sex
Adelie     female    73
           male      73
Gentoo     male      61
           female    58
Chinstrap  male      34
           female    34
dtype: int64

In [247]:
# Jaké jsou minimální a maximální hodnoty délky křídel tučňáků a jak se liší mezi druhy? 
# Který druh má nejmenší rozdíl mezi minimální a maximální délkou křídel?

# 1. Vytvoříme tabulku statistik
stats = penguins.groupby("species")["flipper_length_mm"].agg(["min", "max"])

# 2. Vytvoříme nový sloupec 'rozdil'
stats["rozdil"] = stats["max"] - stats["min"]

# 3. Seřadíme podle rozdílu od nejmenšího
print(stats.sort_values("rozdil"))

             min    max  rozdil
species
Gentoo     203.0  231.0    28.0
Chinstrap  178.0  212.0    34.0
Adelie     172.0  210.0    38.0

In [248]:
# Jaký je medián hmotnosti tučňáků a liší se tento medián mezi jednotlivými ostrovy, kde tučňáci žijí? Na kterém ostrově je medián hmotnosti největší?
# Data seskupte podle názvu ostrova a použijte agregační funkci median() pro výpočet mediánu hmotnosti tučňáků na každém ostrově.

median = penguins.groupby("island")["body_mass_g"].median()
median

island
Biscoe       4775.0
Dream        3687.5
Torgersen    3700.0
Name: body_mass_g, dtype: float64

In [249]:
# Které druhy tučňáků mají průměrnou délku křídel větší než 200 mm?
# 1. Seskupit a spočítat průměr
avg_kridla = penguins.groupby("species")["flipper_length_mm"].mean()

# 2. Zobrazit jen ty nad 200 mm
(avg_kridla[avg_kridla > 200])

species
Gentoo    217.186992
Name: flipper_length_mm, dtype: float64