In [2]:
import pandas as pd

In [3]:
food_nutrient = pd.read_csv("food_nutrient.csv")
food_nutrient #zobrazení náhledu,vždy!!! vypsání DATAFRAME znovu na prázdný řádek

,fdc_id,nutrient_id,amount,data_points,derivation_id,min,max,median,loq,footnote,min_year_acquired,name,unit_name
0,1106032,1257,NaN,NaN,71.0,NaN,NaN,NaN,NaN,NaN,NaN,"Fatty acids, total trans",G
1,1107191,1257,NaN,NaN,70.0,NaN,NaN,NaN,NaN,NaN,NaN,"Fatty acids, total trans",G
2,1107295,1257,NaN,NaN,70.0,NaN,NaN,NaN,NaN,NaN,NaN,"Fatty acids, total trans",G
3,1107475,1257,NaN,NaN,70.0,NaN,NaN,NaN,NaN,NaN,NaN,"Fatty acids, total trans",G
4,1107528,1257,0.0,NaN,70.0,NaN,NaN,NaN,NaN,NaN,NaN,"Fatty acids, total trans",G
...,...,...,...,...,...,...,...,...,...,...,...,...,...
135331,2614074,2068,0.0,NaN,71.0,NaN,NaN,NaN,NaN,NaN,NaN,Vitamin E,MG
135332,2622536,2068,2.0,NaN,70.0,NaN,NaN,NaN,NaN,NaN,NaN,Vitamin E,MG
135333,2622742,2068,13.0,NaN,70.0,NaN,NaN,NaN,NaN,NaN,NaN,Vitamin E,MG
135334,2627542,2068,2.0,NaN,75.0,NaN,NaN,NaN,NaN,NaN,NaN,Vitamin E,MG
135335,2654454,2068,25.0,NaN,70.0,NaN,NaN,NaN,NaN,NaN,NaN,Vitamin E,MG

In [4]:
#food_nutrient.info()
food_nutrient.sample(5) #vypíše random řádek

,fdc_id,nutrient_id,amount,data_points,derivation_id,min,max,median,loq,footnote,min_year_acquired,name,unit_name
32798,888718,1089,24.83,NaN,70.0,NaN,NaN,NaN,NaN,NaN,NaN,"Iron, Fe",MG
85430,931612,1079,10.00,NaN,70.0,NaN,NaN,NaN,NaN,NaN,NaN,"Fiber, total dietary",G
31631,425106,1089,1.67,NaN,75.0,NaN,NaN,NaN,NaN,NaN,NaN,"Iron, Fe",MG
84685,559760,1079,1.60,NaN,70.0,NaN,NaN,NaN,NaN,NaN,NaN,"Fiber, total dietary",G
32512,677634,1089,2.57,NaN,75.0,NaN,NaN,NaN,NaN,NaN,NaN,"Iron, Fe",MG

In [5]:
food_nutrient ["name"] #vypsání sloupce name,prvních pět/posledních pět z datasetu 
food_nutrient ["name"].unique() #chci zjistit jaké neopakující,tedy UNIQUE živiny jsou v datasetu 
food_nutrient ["name"].nunique() #zobrazí počet UNIQUE hodnot v datasetu 
food_nutrient ["name"].value_counts() #pro každou výživnou hodnotu zobrazí, kolikrát se v datasetu vyskytuje
food_nutrient ["name"].value_counts().head(10) #top 10 živin zastoupených v datasetu

name
Protein                         9553
Sodium, Na                      9499
Energy                          9473
Total lipid (fat)               9413
Carbohydrate, by difference     9357
Sugars, total including NLEA    8995
Fatty acids, total saturated    8250
Cholesterol                     8071
Fiber, total dietary            8011
Fatty acids, total trans        8004
Name: count, dtype: int64

In [6]:
# "Magnesium, Mg" (chci najít potraviny s hořčíkem Mg) , #zadání do DataFrame pod proměnnou

podminka = food_nutrient ["name"] == "Magnesium, Mg"

magnesium = food_nutrient[podminka] 

magnesium[["name", "nutrient_id"]]

                 name  nutrient_id
125766  Magnesium, Mg         1090
125767  Magnesium, Mg         1090
125768  Magnesium, Mg         1090
125769  Magnesium, Mg         1090
125770  Magnesium, Mg         1090
...               ...          ...
126155  Magnesium, Mg         1090
126156  Magnesium, Mg         1090
126157  Magnesium, Mg         1090
126158  Magnesium, Mg         1090
126159  Magnesium, Mg         1090

[394 rows x 2 columns]

In [7]:
#magnesium.info ()

magnesium.head ()

magnesium ["amount"].describe() #výpočet min,max,count(počet ne-nulových hodnot),mean(průměrná hodnota),kvartily,std(směrodatná odchylka)

magnesium.describe()

,fdc_id,nutrient_id,amount,data_points,derivation_id,min,max,median,loq,footnote,min_year_acquired
count,3.940000e+02,394.0,394.000000,63.000000,351.000000,6.000000,6.000000,1.0,0.0,0.0,7.000000
mean,1.494746e+06,1090.0,102.079797,2.206349,65.247863,16.716667,21.050000,0.3,NaN,NaN,2014.571429
std,8.224790e+05,0.0,210.755384,3.927401,22.599459,9.994082,12.259486,NaN,NaN,NaN,3.779645
min,1.675510e+05,1090.0,0.000000,0.000000,1.000000,0.300000,0.300000,0.3,NaN,NaN,2006.000000
25%,6.561875e+05,1090.0,13.000000,0.000000,70.000000,12.000000,17.500000,0.3,NaN,NaN,2016.000000
50%,1.674326e+06,1090.0,43.000000,1.000000,75.000000,19.000000,23.500000,0.3,NaN,NaN,2016.000000
75%,2.265302e+06,1090.0,124.250000,1.000000,75.000000,24.500000,25.750000,0.3,NaN,NaN,2016.000000
max,2.661782e+06,1090.0,2941.000000,18.000000,78.000000,26.000000,37.000000,0.3,NaN,NaN,2016.000000

In [8]:
food_nutrient.describe(include="all")

,fdc_id,nutrient_id,amount,data_points,derivation_id,min,max,median,loq,footnote,min_year_acquired,name,unit_name
count,1.353360e+05,135336.000000,135332.000000,4162.000000,132617.000000,418.000000,418.000000,20.000000,48.000000,0.0,127.000000,135336,135336
unique,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,205,7
top,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Protein,G
freq,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9553,69547
mean,1.567766e+06,1171.982894,142.040104,2.008409,70.510025,14.127411,22.791943,5.182550,3.245413,NaN,2014.503937,NaN,NaN
std,7.071883e+05,241.442354,4095.909259,8.560298,8.902334,63.914527,103.101630,22.297075,9.667555,NaN,3.580977,NaN,NaN
min,1.675510e+05,1002.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.005000,NaN,2006.000000,NaN,NaN
25%,1.071067e+06,1008.000000,0.000000,0.000000,70.000000,0.001000,0.008000,0.000000,0.100000,NaN,2016.000000,NaN,NaN
50%,1.660490e+06,1093.000000,3.850000,0.000000,70.000000,0.050000,0.133000,0.008500,0.247500,NaN,2016.000000,NaN,NaN
75%,2.151470e+06,1253.000000,40.000000,1.000000,75.000000,1.215500,2.792750,0.305000,1.370000,NaN,2016.000000,NaN,NaN
max,2.662182e+06,2068.000000,857143.000000,197.000000,79.000000,816.000000,1340.000000,99.900000,40.000000,NaN,2016.000000,NaN,NaN

In [9]:
podminka2=magnesium ["amount"] > 100

#magnesium ["amount"] > 100
magnesium_limit = magnesium[podminka2] 
magnesium_limit["amount"].describe()

count     117.000000
mean      270.367521
std       328.783353
min       102.000000
25%       143.000000
50%       178.000000
75%       268.000000
max      2941.000000
Name: amount, dtype: float64

In [10]:
# "Calcium, Ca", mezi 30 a 500

podminka1 = food_nutrient["name"] == "Calcium, Ca"
#food_nutrient["name"] == "Calcium, Ca" (průběžná kontrola kodu,zda ho mám správně,zavolám podmínku)
podminka2 = food_nutrient["amount"] > 30
podminka2
podminka3= food_nutrient["amount"] < 500

food_nutrient[podminka1 & podminka2 & podminka3] #ve staré verzi musím dát podmínky do ()

food_nutrient[
    (food_nutrient["name"] == "Calcium, Ca") &
    (food_nutrient["amount"] > 30) &
    (food_nutrient["amount"] < 500)] #bez proměnných MUSÍM napsat () a nesmím zapomenout na &


# & AND ampersand
# | OR "pajpa"

# == rovná se, POZOR!!!! Jedno rovnítko (=) slouží k přiřazení hodnoty do proměnné. Dvě rovnítka (==) slouží k porovnání.
# >
# >=
# <
# <=
# != nerovná se


# možné způsoby zápisu :

calcium_limit = food_nutrient[(food_nutrient["name"] == "Calcium, Ca") & (food_nutrient["amount"] > 30) & (food_nutrient["amount"] < 500)]

calcium_limit = food_nutrient.query('name == "Calcium, Ca" and 30 < amount < 500')

calcium_limit = food_nutrient[(food_nutrient["name"] == "Calcium, Ca") & food_nutrient["amount"].between(30, 500, inclusive="neither")]

calcium_limit = food_nutrient.loc[(food_nutrient["name"] == "Calcium, Ca") & (food_nutrient["amount"] > 30) & (food_nutrient["amount"] < 500)]

In [11]:
# %time print("Ahoj") # %TIME změří rychlost kodu (magic commons)
# %%time změří celou bunku 
%time calcium_limit = food_nutrient[(food_nutrient["name"] == "Calcium, Ca") & (food_nutrient["amount"] > 30) & (food_nutrient["amount"] < 500)]
%time calcium_limit = food_nutrient.query('name == "Calcium, Ca" and 30 < amount < 500')
%time calcium_limit = food_nutrient[(food_nutrient["name"] == "Calcium, Ca") & food_nutrient["amount"].between(30, 500, inclusive="neither")]
%time calcium_limit = food_nutrient.loc[(food_nutrient["name"] == "Calcium, Ca") & (food_nutrient["amount"] > 30) & (food_nutrient["amount"] < 500)]

CPU times: total: 15.6 ms
Wall time: 15.4 ms
CPU times: total: 15.6 ms
Wall time: 10.6 ms
CPU times: total: 15.6 ms
Wall time: 12 ms
CPU times: total: 0 ns
Wall time: 14.3 ms

In [12]:
import pandas as pd

In [13]:
url_food_nutrient = "https://kodim.cz/cms/assets/czechitas/python-data-1/python-pro-data-1/podmineny-vyber/podmineny-vyber/food_nutrient.csv"
food_nutrient = pd.read_csv(url_food_nutrient)

In [14]:
# CVIČENÍ Vláknina, Fiber
food_nutrient[(food_nutrient["name"] == "Fiber, total dietary")
    & (food_nutrient["amount"] >= 10)]

,fdc_id,nutrient_id,amount,data_points,derivation_id,min,max,median,loq,footnote,min_year_acquired,name,unit_name
83639,1109336,1079,10.0,NaN,70.0,NaN,NaN,NaN,NaN,NaN,NaN,"Fiber, total dietary",G
83666,1114461,1079,10.7,NaN,70.0,NaN,NaN,NaN,NaN,NaN,NaN,"Fiber, total dietary",G
83667,1114961,1079,10.0,NaN,70.0,NaN,NaN,NaN,NaN,NaN,NaN,"Fiber, total dietary",G
83675,1117734,1079,10.0,NaN,70.0,NaN,NaN,NaN,NaN,NaN,NaN,"Fiber, total dietary",G
83681,1118500,1079,11.1,NaN,70.0,NaN,NaN,NaN,NaN,NaN,NaN,"Fiber, total dietary",G
...,...,...,...,...,...,...,...,...,...,...,...,...,...
91545,2638057,1079,15.0,NaN,70.0,NaN,NaN,NaN,NaN,NaN,NaN,"Fiber, total dietary",G
91584,2651678,1079,39.5,NaN,70.0,NaN,NaN,NaN,NaN,NaN,NaN,"Fiber, total dietary",G
91598,2654454,1079,10.7,NaN,70.0,NaN,NaN,NaN,NaN,NaN,NaN,"Fiber, total dietary",G
91599,2654695,1079,11.8,NaN,70.0,NaN,NaN,NaN,NaN,NaN,NaN,"Fiber, total dietary",G
91629,2660613,1079,10.0,NaN,70.0,NaN,NaN,NaN,NaN,NaN,NaN,"Fiber, total dietary",G

In [15]:
# cvičení HLÁŠENÍ CHYB
errors = food_nutrient[(food_nutrient["unit_name"] == "MG") & (food_nutrient["amount"] > 100_000)]
errors

,fdc_id,nutrient_id,amount,data_points,derivation_id,min,max,median,loq,footnote,min_year_acquired,name,unit_name
18231,1048385,1092,101770.0,NaN,70.0,NaN,NaN,NaN,NaN,NaN,NaN,"Potassium, K",MG
18888,1527945,1092,176991.0,NaN,70.0,NaN,NaN,NaN,NaN,NaN,NaN,"Potassium, K",MG
63254,944746,1093,282828.0,NaN,70.0,NaN,NaN,NaN,NaN,NaN,NaN,"Sodium, Na",MG
65700,1599725,1093,323944.0,NaN,70.0,NaN,NaN,NaN,NaN,NaN,NaN,"Sodium, Na",MG
67418,1982925,1093,203125.0,NaN,70.0,NaN,NaN,NaN,NaN,NaN,NaN,"Sodium, Na",MG
68232,2149015,1093,415625.0,NaN,70.0,NaN,NaN,NaN,NaN,NaN,NaN,"Sodium, Na",MG
69486,2465074,1093,528986.0,NaN,70.0,NaN,NaN,NaN,NaN,NaN,NaN,"Sodium, Na",MG
69528,2472749,1093,857143.0,NaN,70.0,NaN,NaN,NaN,NaN,NaN,NaN,"Sodium, Na",MG
69647,2495397,1093,183333.0,NaN,70.0,NaN,NaN,NaN,NaN,NaN,NaN,"Sodium, Na",MG

In [16]:
errors.to_csv("error_reports.csv")
# errors.to_csv("error_reports.csv", index=False)

In [17]:
# CVIČENÍ Česká jména 
url = "https://kodim.cz/cms/assets/czechitas/python-data-1/python-pro-data-1/podmineny-vyber/podmineny-vyber/ceska-jmena/jmena.csv"
jmena = pd.read_csv(url)

In [18]:
jmena[jmena["prumerny_vek"] > 60] #Vypiš všechny řádky se jmény, jejichž nositelé mají průměrný věk vyšší než 60.

jmena[(jmena["cetnost"] >= 80_000) & (jmena["cetnost"] <= 100_000)] #Vypiš pouze jména z těch řádků, kde četnost je mezi 80 000 a 100 000.

jmena[(jmena["puvod"] == "slovanský") | (jmena["puvod"] == "hebrejský")] #Pokud jsi vytvořil(a) i verzi s operátorem |, můžeš obě verze porovnat a rozhodnout se, která verze se ti líbí více.
# jmena[jmena["puvod"].isin(["slovanský", "hebrejský"])]

        jmeno  cetnost  prumerny_vek pohlavi      puvod
1         Jan   293938            40       m  hebrejský
3        Jana   264944            50       ž  hebrejský
4       Marie   260526            65       ž  hebrejský
5       Josef   211317            57       m  hebrejský
9    Jaroslav   172785            55       m  slovanský
10        Eva   152463            53       ž  hebrejský
11   Miroslav   147753            52       m  slovanský
12       Hana   145901            51       ž  hebrejský
13       Anna   134819            51       ž  hebrejský
14     Zdeněk   126094            54       m  slovanský
15     Václav   123927            51       m  slovanský
16     Michal   123324            32       m  hebrejský
21      Jakub   108013            19       m  hebrejský
22      Milan   107458            51       m  slovanský
23       Věra   107388            63       ž  slovanský
24      Alena   105093            55       ž  hebrejský
28      David   101311            25       m  hebrejský
30  Jaroslava    84556            63       ž  slovanský
31   Vladimír    83762            56       m  slovanský
34   Michaela    78823            28       ž  hebrejský
35      Jitka    78187            51       ž  hebrejský
38    Ludmila    72750            65       ž  slovanský
39   Ladislav    69797            55       m  slovanský
40     Zdeňka    69060            61       ž  slovanský
41      Ivana    68917            49       ž  slovanský
45  Stanislav    61889            54       m  slovanský
46     Eliška    61517            24       ž  hebrejský
47     Zuzana    61382            34       ž  hebrejský
48     Daniel    60935            23       m  hebrejský
50    Jarmila    59666            65       ž  slovanský
51      Radek    58589            36       m  slovanský
56    Vojtěch    52802            22       m  slovanský
58       Dana    50781            51       ž  hebrejský
61       Adam    47837            14       m  hebrejský
64     Vlasta    41736            68       ž  slovanský
66  Miroslava    41151            54       ž  slovanský
68     Božena    39851            72       ž  slovanský
70     Libuše    39269            66       ž  slovanský
72      Matěj    38519            13       m  hebrejský
73      Šárka    38339            37       ž  slovanský
82   Miloslav    32769            60       m  slovanský
84   Gabriela    31175            33       ž  hebrejský
85    Jaromír    30984            55       m  slovanský
89      Aneta    29840            17       ž  hebrejský
90     Simona    29618            30       ž  hebrejský
91     Růžena    28952            69       ž  slovanský
92      Radka    26939            38       ž  slovanský
93    Daniela    26536            38       ž  hebrejský
96  Vlastimil    26014            54       m  slovanský
97        Iva    26003            46       ž  slovanský
98      Miloš    25509            53       m  slovanský
99     Zdenka    25416            68       ž  slovanský

In [19]:
# CVIČENÍ Dvě kritéria
# Chceme vybrat potraviny, které splňují dvě kritéria:
# nízký obsah nasycených mastných kyselin (Fatty acids, total saturated, uvažuj méně než 1 gram),
# vysoký obsah vlákniny (Fiber, total dietary, uvažuj více než 5 gramů).


food_nutrient_filtered = food_nutrient[(food_nutrient["name"] == "Fatty acids, total saturated") 
                                      & (food_nutrient["amount"] < 1) 
                                      | (food_nutrient["name"] == "Fiber, total dietary") 
                                      & (food_nutrient["amount"] > 4)]

food_nutrient_filtered["name"].value_counts()

name
Fatty acids, total saturated    3405
Fiber, total dietary            1682
Name: count, dtype: int64

In [20]:
import pandas as pd
food_nutrient = pd.read_csv("food_nutrient.csv")
food_nutrient
# NaN NULL None - chybějící hodnota (missing value) 


# .isna() (je NA),výsledek True/False , #.notna(), #.dropna(), #.fillna()

# food_nutrient["amount"].isna()

food_nutrient[food_nutrient["amount"].isna()] #vypíše pouze ty čtyři hodnoty s NaN ve sloupci amount 
food_nutrient[food_nutrient["amount"].notna()] #vypíše pouze hodnoty BEZ NaN ve sloupci amount 

food_nutrient.dropna(subset="amount") #dostanu prázdnou tabulku,protože v každém řádku je alespon jedna hodnota NaN , subset se koukne pouze do zadaného sloupce amount

food_nutrient["amount"] = food_nutrient ["amount"].fillna("XXXXXX") #vyber sloupec amount a dopln do něj "XXXXXX",do sloupce amount přiřazuje hodnoty vyplněného sloupce amount, ostatní hodnoty jsou stejné,neřeším je
food_nutrient

,fdc_id,nutrient_id,amount,data_points,derivation_id,min,max,median,loq,footnote,min_year_acquired,name,unit_name
0,1106032,1257,XXXXXX,NaN,71.0,NaN,NaN,NaN,NaN,NaN,NaN,"Fatty acids, total trans",G
1,1107191,1257,XXXXXX,NaN,70.0,NaN,NaN,NaN,NaN,NaN,NaN,"Fatty acids, total trans",G
2,1107295,1257,XXXXXX,NaN,70.0,NaN,NaN,NaN,NaN,NaN,NaN,"Fatty acids, total trans",G
3,1107475,1257,XXXXXX,NaN,70.0,NaN,NaN,NaN,NaN,NaN,NaN,"Fatty acids, total trans",G
4,1107528,1257,0.0,NaN,70.0,NaN,NaN,NaN,NaN,NaN,NaN,"Fatty acids, total trans",G
...,...,...,...,...,...,...,...,...,...,...,...,...,...
135331,2614074,2068,0.0,NaN,71.0,NaN,NaN,NaN,NaN,NaN,NaN,Vitamin E,MG
135332,2622536,2068,2.0,NaN,70.0,NaN,NaN,NaN,NaN,NaN,NaN,Vitamin E,MG
135333,2622742,2068,13.0,NaN,70.0,NaN,NaN,NaN,NaN,NaN,NaN,Vitamin E,MG
135334,2627542,2068,2.0,NaN,75.0,NaN,NaN,NaN,NaN,NaN,NaN,Vitamin E,MG
135335,2654454,2068,25.0,NaN,70.0,NaN,NaN,NaN,NaN,NaN,NaN,Vitamin E,MG