In [7]:
import pandas as pd

In [8]:
# Vytvoření prázdného DataFrame
prazdny_df= pd.DataFrame()
dataframe_se_sloupecky = pd.DataFrame (columns=["sloupec1","sloupec2","sloupec3"])
dataframe_se_sloupecky

Empty DataFrame
Columns: [sloupec1, sloupec2, sloupec3]
Index: []

In [9]:
# Načítání dat
novy_dataframe = pd.read_csv("branded_food.csv")
novy_dataframe
novy_dataframe.head(3)
# Další parametry při načítání CSV
# novy_dataframe = pd.read_csv("branded_food.csv", sep=";") PRO SOUBORY ODDĚLENÉ STŘEDNÍKEM

,fdc_id,brand_owner,brand_name,subbrand_name,gtin_upc,ingredients,not_a_significant_source_of,serving_size,serving_size_unit,household_serving_fulltext,branded_food_category,data_source,package_weight,modified_date,available_date,market_country,discontinued_date,preparation_state_code,trade_channel,short_description
0,1106032,BRAKEBUSH BROTHERS INC.,NaN,NaN,10038034720202,INGREDIENTS: BONELESS CHICKEN BREAST MEAT WITH...,NaN,85.0,g,NaN,Meat/Poultry/Other Animals Prepared/Processed,GDSN,NaN,2020-09-03,2020-11-13,United States,NaN,NaN,NaN,NaN
1,1107191,Mahco Inc,NaN,NaN,877448001674,"TOMATO PUREE (TOMATOES), CARROTS, ONIONS, SUN-...",NaN,125.0,g,NaN,Prepared Pasta & Pizza Sauces,LI,NaN,2020-09-22,2020-11-13,United States,NaN,NaN,NaN,NaN
2,1107295,Hormel Foods Corporation,NaN,NaN,37600665605,MASA FLOUR (GROUND WHITE CORN WITH A TRACE OF ...,NaN,30.0,g,NaN,"Chips, Pretzels & Snacks",LI,NaN,2020-04-08,2020-11-13,United States,NaN,NaN,NaN,NaN

In [11]:
# Indexy
muj_dataframe.set_index("sloupecek", inplace=True) # nastaví nový index
muj_dataframe.reset_index(inplace=True) # resetuje index zpět na implicitní

NameError: name 'muj_dataframe' is not defined

In [ ]:
# Základní informace o tabulce
muj_dataframe.info() # základní informace o DataFrame (sloupce, typy, chybějící data)
muj_dataframe.shape # (počet řádků, počet sloupců)
muj_dataframe.columns # názvy všech sloupců
muj_dataframe.describe(include="all") # souhrnné statistiky včetně kategorií

muj_dataframe.head(10) # prvních 10 řádků
muj_dataframe.tail(3) # poslední 3 řádky
muj_dataframe.sample(5) # 5 náhodných řádků

In [ ]:
# Výběr sloupců
muj_dataframe["Nazev sloupce"] # vrací Series (jednosloupcová struktura)
muj_dataframe[["Nazev sloupce", "Dalsi nazev sloupce"]] # vrací DataFrame (vícesloupcová struktura)

In [ ]:
# Výběr řádků pomocí indexu
muj_dataframe.iloc[1:10]    # řádky 1 až 9 (0-based indexování)
muj_dataframe.iloc[:3]      # první tři řádky
muj_dataframe.iloc[-3:]     # poslední tři řádky
muj_dataframe.iloc[8:]      # od osmé řádky dále

In [ ]:
# Výběr řádků i sloupců
muj_dataframe.iloc[:, [0, 3]] # všechny řádky a pouze sloupce 0 a 3
muj_dataframe.loc[1:4, ["Nazev Sloupce"]] # vybraný rozsah řádků a sloupce podle názvu