In [18]:
import pandas as pd

In [19]:
titanic = pd.read_csv("titanic.csv")
titanic
titanic.columns
titanic.shape
titanic.info()

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    str
 4   Sex          891 non-null    str
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    str
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    str
 11  Embarked     889 non-null    str
dtypes: float64(2), int64(5), str(5)
memory usage: 83.7 KB

In [ ]:
import pandas as pd
data_aapl = pd.read_csv("aapl_daily_2y.csv")
data_aapl = data_aapl.set_index("date") #stanovení indexu date
# data_aapl

data_aapl.shape[0]  # počet řádků v tabulce
data_aapl.shape[1]  # počet sloupců v tabulce
data_aapl.columns  # názvy všech sloupců

start_date = data_aapl.index[0]  # datum začátku sledovaného období
start_date
end_date = data_aapl.index[-1]  # datum konce sledovaného období
end_date

data_aapl.head()
data_aapl.tail()

start_close = data_aapl["close"].iat[0]  # zavírací cena na začátku období
end_close = data_aapl["close"].iat[-1]  # zavírací cena na konci období

initial_investment = 9000  # výchozí investice v USD
share_count = initial_investment / start_close  # počet nakoupených akcií
final_value = share_count * end_close  # hodnota investice na konci období

profit_percent = (final_value - initial_investment) / initial_investment * 100  # zisk v procentech

,open,high,low,close,volume,vwap,transactions
date,,,,,,,
2025-10-20,255.885,264.375,255.6300,262.24,90483029.0,261.7003,1160822
2025-10-21,261.880,265.290,261.8300,262.77,46695748.0,263.4176,714945
2025-10-22,262.650,262.850,255.4300,258.45,45011970.0,258.6829,687110
2025-10-23,259.940,260.620,258.0101,259.58,32752139.0,259.5770,482428
2025-10-24,261.190,264.130,259.1800,262.82,38253517.0,262.5390,599532

In [ ]:
import pandas as pd
postavy = pd.read_csv("character-deaths.csv")
postavy = postavy.set_index("Name")
# postavy
postavy.columns
hali = postavy.loc ["Hali"]
usek = postavy.loc ["Gevin Harlaw" : "Gillam"]
deaths = postavy.loc ["Gevin Harlaw" : "Gillam","Death Year"]
books = postavy.loc ["Gevin Harlaw" : "Gillam", "GoT" : "DwD"]
# books

                     GoT  CoK  SoS  FfC  DwD
Name
Gevin Harlaw           0    1    0    0    0
Ghael                  0    0    1    0    1
Ghost of High Heart    0    0    1    0    0
Gillam                 0    0    0    1    0

In [51]:
import pandas as pd
food_nutrient = pd.read_csv("food_nutrient.csv")
food_nutrient[(food_nutrient["name"] == "Fiber, total dietary")
      & (food_nutrient["amount"] >= 10)]

,fdc_id,nutrient_id,amount,data_points,derivation_id,min,max,median,loq,footnote,min_year_acquired,name,unit_name
83639,1109336,1079,10.0,NaN,70.0,NaN,NaN,NaN,NaN,NaN,NaN,"Fiber, total dietary",G
83666,1114461,1079,10.7,NaN,70.0,NaN,NaN,NaN,NaN,NaN,NaN,"Fiber, total dietary",G
83667,1114961,1079,10.0,NaN,70.0,NaN,NaN,NaN,NaN,NaN,NaN,"Fiber, total dietary",G
83675,1117734,1079,10.0,NaN,70.0,NaN,NaN,NaN,NaN,NaN,NaN,"Fiber, total dietary",G
83681,1118500,1079,11.1,NaN,70.0,NaN,NaN,NaN,NaN,NaN,NaN,"Fiber, total dietary",G
...,...,...,...,...,...,...,...,...,...,...,...,...,...
91545,2638057,1079,15.0,NaN,70.0,NaN,NaN,NaN,NaN,NaN,NaN,"Fiber, total dietary",G
91584,2651678,1079,39.5,NaN,70.0,NaN,NaN,NaN,NaN,NaN,NaN,"Fiber, total dietary",G
91598,2654454,1079,10.7,NaN,70.0,NaN,NaN,NaN,NaN,NaN,NaN,"Fiber, total dietary",G
91599,2654695,1079,11.8,NaN,70.0,NaN,NaN,NaN,NaN,NaN,NaN,"Fiber, total dietary",G
91629,2660613,1079,10.0,NaN,70.0,NaN,NaN,NaN,NaN,NaN,NaN,"Fiber, total dietary",G

In [52]:
errors = food_nutrient[(food_nutrient["unit_name"] == "MG") & (food_nutrient["amount"] > 100_000)]
errors.to_csv("error_reports.csv")

In [ ]:
url = "https://kodim.cz/cms/assets/czechitas/python-data-1/python-pro-data-1/podmineny-vyber/podmineny-vyber/ceska-jmena/jmena.csv"
jmena = pd.read_csv(url)

jmena[jmena["prumerny_vek"] > 60] #Vypiš všechny řádky se jmény, jejichž nositelé mají průměrný věk vyšší než 60.
jmena[(jmena["cetnost"] >= 80_000) & (jmena["cetnost"] <= 100_000)] #Vypiš pouze jména z těch řádků, kde četnost je mezi 80 000 a 100 000.
# jmena[(jmena["puvod"] == "slovanský") | (jmena["puvod"] == "hebrejský")]  # Vypiš jména a četnost pro jména se slovanským nebo hebrejským původem.
jmena = jmena[jmena["puvod"].isin(["slovanský", "hebrejský"])] # Vypiš jména a četnost pro jména se slovanským nebo hebrejským původem.
jmena

        jmeno  cetnost  prumerny_vek pohlavi      puvod
1         Jan   293938            40       m  hebrejský
3        Jana   264944            50       ž  hebrejský
4       Marie   260526            65       ž  hebrejský
5       Josef   211317            57       m  hebrejský
9    Jaroslav   172785            55       m  slovanský
10        Eva   152463            53       ž  hebrejský
11   Miroslav   147753            52       m  slovanský
12       Hana   145901            51       ž  hebrejský
13       Anna   134819            51       ž  hebrejský
14     Zdeněk   126094            54       m  slovanský
15     Václav   123927            51       m  slovanský
16     Michal   123324            32       m  hebrejský
21      Jakub   108013            19       m  hebrejský
22      Milan   107458            51       m  slovanský
23       Věra   107388            63       ž  slovanský
24      Alena   105093            55       ž  hebrejský
28      David   101311            25       m  hebrejský
30  Jaroslava    84556            63       ž  slovanský
31   Vladimír    83762            56       m  slovanský
34   Michaela    78823            28       ž  hebrejský
35      Jitka    78187            51       ž  hebrejský
38    Ludmila    72750            65       ž  slovanský
39   Ladislav    69797            55       m  slovanský
40     Zdeňka    69060            61       ž  slovanský
41      Ivana    68917            49       ž  slovanský
45  Stanislav    61889            54       m  slovanský
46     Eliška    61517            24       ž  hebrejský
47     Zuzana    61382            34       ž  hebrejský
48     Daniel    60935            23       m  hebrejský
50    Jarmila    59666            65       ž  slovanský
51      Radek    58589            36       m  slovanský
56    Vojtěch    52802            22       m  slovanský
58       Dana    50781            51       ž  hebrejský
61       Adam    47837            14       m  hebrejský
64     Vlasta    41736            68       ž  slovanský
66  Miroslava    41151            54       ž  slovanský
68     Božena    39851            72       ž  slovanský
70     Libuše    39269            66       ž  slovanský
72      Matěj    38519            13       m  hebrejský
73      Šárka    38339            37       ž  slovanský
82   Miloslav    32769            60       m  slovanský
84   Gabriela    31175            33       ž  hebrejský
85    Jaromír    30984            55       m  slovanský
89      Aneta    29840            17       ž  hebrejský
90     Simona    29618            30       ž  hebrejský
91     Růžena    28952            69       ž  slovanský
92      Radka    26939            38       ž  slovanský
93    Daniela    26536            38       ž  hebrejský
96  Vlastimil    26014            54       m  slovanský
97        Iva    26003            46       ž  slovanský
98      Miloš    25509            53       m  slovanský
99     Zdenka    25416            68       ž  slovanský

In [60]:
food_nutrient_filtered = food_nutrient[(food_nutrient["name"] == "Fatty acids, total saturated") 
                                      & (food_nutrient["amount"] < 1) 
                                      | (food_nutrient["name"] == "Fiber, total dietary") 
                                      & (food_nutrient["amount"] > 4)]

food_nutrient_filtered["name"].value_counts()

name
Fatty acids, total saturated    3405
Fiber, total dietary            1682
Name: count, dtype: int64